services:
  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_BASE_URL: ${VITE_API_BASE_URL}
    image: bytenboard-frontend
    container_name: byte_boards_frontend
    restart: unless-stopped
    ports:
      - "5173:80"

  backend:
    build: ./backend
    image: bytenboard-backend
    container_name: byte_boards_backend
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "3003:5000"
    networks:
      - global-db-net

networks:
  global-db-net:
    external: true
