# ~/bytenboard/docker-compose.yml
services:
  frontend:
    image: bytenboard-frontend
    container_name: byte_boards_frontend
    restart: unless-stopped
    ports:
      - "5173:80"

  backend:
    image: bytenboard-backend
    container_name: byte_boards_backend
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "3003:3000" 
    networks:
      - global-db-net

networks:
  global-db-net:
    external: true
