services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: byte_boards_backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    environment:
      NODE_ENV: production
    networks:
      - byte_boards_net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: byte_boards_frontend
    restart: unless-stopped
    ports:
      - "5173:80"
    depends_on:
      - backend
    networks:
      - byte_boards_net 
networks:
  byte_boards_net:
    external: true
